# Generated by Django 2.0.2 on 2018-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0005_auto_20180304_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='allow_add',
            field=models.IntegerField(default=0),
        ),
    ]
