# Generated by Django 2.0.2 on 2018-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0006_table_allow_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('rows', models.TextField(default=0)),
                ('title', models.TextField()),
                ('counts', models.IntegerField(default=0)),
                ('pub_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='allow_null',
            field=models.IntegerField(default=0),
        ),
    ]
