# Generated by Django 2.0.2 on 2018-03-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0007_auto_20180315_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('rows', models.TextField(default=0)),
                ('title', models.TextField()),
                ('counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
